config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :orders
  resources :delivery_people
  resources :dishes
  resources :restaurants
  resources :addresses
  resources :users
  
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[ show edit update destroy ]

  # GET /dishes or /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1 or /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes or /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully created." }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1 or /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully updated." }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1 or /dishes/1.json
  def destroy
    @dish.destroy!

    respond_to do |format|
      format.html { redirect_to dishes_url, notice: "Dish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.require(:dish).permit(:restaurant_id, :name, :price)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">
  <p>
    <strong>Restaurant:</strong>
    <%= dish.restaurant_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= dish.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= dish.price %>
  </p>

</div>

app/views/dishes/_form.html.erb
<%= form_with(model: dish) do |form| %>
  <% if dish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :restaurant_id, style: "display: block" %>
    <%= form.text_field :restaurant_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render "form", dish: @dish %>

<br>

<div>
  <%= link_to "Show this dish", @dish %> |
  <%= link_to "Back to dishes", dishes_path %>
</div>

app/views/dishes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dishes</h1>

<div id="dishes">
  <% @dishes.each do |dish| %>
    <%= render dish %>
    <p>
      <%= link_to "Show this dish", dish %>
    </p>
  <% end %>
</div>

<%= link_to "New dish", new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render "form", dish: @dish %>

<br>

<div>
  <%= link_to "Back to dishes", dishes_path %>
</div>

app/views/dishes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dish %>

<div>
  <%= link_to "Edit this dish", edit_dish_path(@dish) %> |
  <%= link_to "Back to dishes", dishes_path %>

  <%= button_to "Destroy this dish", @dish, method: :delete %>
</div>